#!/usr/bin/env python3
"""Sync AXIOM count-domain metadata from axiom_count_spec into public.axiom_artifacts (idempotent).

When psycopg2/SQLAlchemy cannot load locally (common on Windows + Python 3.14), use --emit-sql
and apply the generated file with psql or your migration runner instead of connecting from Python.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.services.axiom_count_spec import (  # noqa: E402
    ARTIFACT_COUNT_METADATA,
    CATEGORY_DEFAULT_METADATA,
    metadata_for_artifact,
)


def _jsonb_sql(value: dict) -> str:
    """Escape JSON for a PostgreSQL string literal."""
    return json.dumps(value).replace("'", "''")


def _category_where(category_key: str) -> str:
    key = category_key.lower()
    if key == "documents":
        return "category = 'Documents'"
    if "email" in key:
        return "category ILIKE '%Email%'"
    if key == "communication":
        return "category = 'Communication'"
    return f"lower(category) LIKE '%{key.replace(' ', '%')}%'"


def emit_sql_updates() -> str:
    """Build idempotent SQL without a database connection."""
    lines = [
        "-- AXIOM count metadata sync (generated by sync_axiom_count_spec.py --emit-sql)",
        "-- Apply: psql $DATABASE_URL -f migrations/024_axiom_count_metadata_sync.sql",
        "",
    ]
    for name, meta in sorted(ARTIFACT_COUNT_METADATA.items()):
        payload = _jsonb_sql(meta)
        safe_name = name.replace("'", "''")
        lines.append(
            "UPDATE public.axiom_artifacts\n"
            f"SET metadata = metadata || '{payload}'::jsonb, updated_at = NOW()\n"
            f"WHERE lower(regexp_replace(trim(artifact_name), '\\s+', ' ', 'g')) = '{safe_name}';\n"
        )
    for category_key, meta in sorted(CATEGORY_DEFAULT_METADATA.items()):
        payload = _jsonb_sql(meta)
        lines.append(
            "UPDATE public.axiom_artifacts\n"
            f"SET metadata = metadata || '{payload}'::jsonb, updated_at = NOW()\n"
            f"WHERE {_category_where(category_key)};\n"
        )
    return "\n".join(lines)


def _open_db_session():
    try:
        from app.db.session import SessionLocal
    except ImportError as exc:
        raise SystemExit(
            "Could not import the database driver (psycopg2). "
            "On Windows this often means psycopg2-binary has no wheel for your Python version.\n\n"
            "Workaround — generate SQL without connecting:\n"
            "  python scripts/sync_axiom_count_spec.py --emit-sql --output migrations/024_axiom_count_metadata_sync.sql\n"
            "Then apply with psql or your migration tool.\n\n"
            f"Original error: {exc}"
        ) from exc
    return SessionLocal()


def sync_metadata(*, dry_run: bool = False) -> int:
    from sqlalchemy import text

    updated = 0
    SessionLocal = _open_db_session()
    with SessionLocal() as db:
        rows = db.execute(
            text("SELECT artifact_id, artifact_name, category, metadata FROM public.axiom_artifacts")
        ).mappings().all()
        for row in rows:
            meta = metadata_for_artifact(
                artifact_name=str(row.get("artifact_name") or ""),
                category=str(row.get("category") or ""),
            )
            existing = row.get("metadata") or {}
            if isinstance(existing, str):
                try:
                    existing = json.loads(existing)
                except json.JSONDecodeError:
                    existing = {}
            merged = {**existing, **meta}
            if merged == existing:
                continue
            updated += 1
            if dry_run:
                print(f"would update {row['artifact_id']}: {meta}")
                continue
            db.execute(
                text(
                    """UPDATE public.axiom_artifacts
                       SET metadata = CAST(:meta AS jsonb), updated_at = NOW()
                       WHERE artifact_id = :aid"""
                ),
                {"aid": row["artifact_id"], "meta": json.dumps(merged)},
            )
        if not dry_run:
            db.commit()
    return updated


def main() -> None:
    parser = argparse.ArgumentParser(description="Sync AXIOM count metadata to axiom_artifacts")
    parser.add_argument("--dry-run", action="store_true", help="Preview DB updates without writing")
    parser.add_argument(
        "--emit-sql",
        action="store_true",
        help="Write SQL UPDATE statements (no database connection required)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="File path for --emit-sql (default: stdout)",
    )
    parser.add_argument("--list-keys", action="store_true", help="Print known artifact metadata keys")
    args = parser.parse_args()

    if args.list_keys:
        print("artifact keys:", len(ARTIFACT_COUNT_METADATA))
        print("category defaults:", list(CATEGORY_DEFAULT_METADATA.keys()))
        return

    if args.emit_sql:
        sql = emit_sql_updates()
        if args.output:
            args.output.write_text(sql, encoding="utf-8")
            print(f"Wrote SQL to {args.output}")
        else:
            print(sql)
        return

    count = sync_metadata(dry_run=args.dry_run)
    print(f"{'Would update' if args.dry_run else 'Updated'} {count} artifact metadata row(s)")


if __name__ == "__main__":
    main()
