-- AXIOM count metadata sync (generated by sync_axiom_count_spec.py --emit-sql)
-- Apply: psql $DATABASE_URL -f migrations/024_axiom_count_metadata_sync.sql

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "LOGFILE_ANALYSIS_WHERE", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = '$logfile analysis';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "registry_value", "query_key": "FEATURE_USAGE_REGISTRY", "parser_family": "registry"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'feature usage';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "JUMP_LIST_WHERE", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'jump list';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "JUMP_LIST_WHERE", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'jump lists';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "LNK_FILE_WHERE", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'lnk files';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "LOGFILE_ANALYSIS_WHERE", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'logfile analysis';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "visit", "query_key": "URL_VISIT_MALWARE", "parser_family": "sqlite"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'malware/phishing urls';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "connection", "query_key": "RDP_REGISTRY", "parser_family": "registry"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'remote desktop protocol';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "connection", "query_key": "RDP_REGISTRY", "parser_family": "registry"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'remote desktop protocol (rdp)';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "visit", "query_key": "URL_VISIT_SOCIAL", "parser_family": "sqlite"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'social media urls';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "registry_value", "query_key": "USB_REGISTRY_SETUPAPI", "parser_family": "registry", "axiom_reconciliation_group": "USB_DEVICES"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'usb devices';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "visit", "query_key": "URL_VISIT_WEB_CHAT", "parser_family": "sqlite"}'::jsonb, updated_at = NOW()
WHERE lower(regexp_replace(trim(artifact_name), '\s+', ' ', 'g')) = 'web chat urls';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "visit", "query_key": "URL_VISIT_CATEGORY", "parser_family": "sqlite"}'::jsonb, updated_at = NOW()
WHERE category = 'Communication';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "file_occurrence", "record_unit": "file_entry", "query_key": "DOCUMENT_EXTENSION", "parser_family": "path_inventory"}'::jsonb, updated_at = NOW()
WHERE category = 'Documents';

UPDATE public.axiom_artifacts
SET metadata = metadata || '{"count_domain": "artifact_record", "record_unit": "message", "query_key": "OUTLOOK_EMAIL_WHERE", "parser_family": "sqlite"}'::jsonb, updated_at = NOW()
WHERE category ILIKE '%Email%';
