"""Export a complete SQL bundle from the live Postgres (schema + static/master data).

Assumes forensic jobs have already been deleted. Job tables are included in DDL
with empty (or zero-row) data sections.

Output: database_sql/
  00_README.md
  01_extensions_and_schema.sql   — CREATE EXTENSION / TABLE / INDEX / FUNCTION / TRIGGER
  02_data_public_master.sql      — public catalogs + platform RBAC + firms
  03_data_firm_aetheris.sql      — firm IAM, roles, rights, users (no job rows expected)
  run-all.ps1 / run-all.sh

Usage (host with docker compose postgres running):
  python scripts/export_database_sql_bundle.py
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "database_sql"
COMPOSE = REPO / "docker-compose.yml"

PUBLIC_DATA_TABLES = (
    "firms",
    "platform_permissions",
    "platform_roles",
    "platform_role_permissions",
    "platform_users",
    "platform_user_roles",
    "axiom_objectives",
    "axiom_procedures",
    "axiom_artifacts",
    "encyclopedia_artifacts",
    "encyclopedia_field_rows",
    "encyclopedia_sections",
    "encyclopedia_relationships",
    "report_type_templates",
    "case_types",
    "report_type_mandatory_areas",
    "reports_artifacts",
    "reports_objective",
    "investigation_area_templates",
    "artifact_investigation_area_map",
    "cisa_kev_catalog",
)

# Firm tables that are master/IAM/config — NOT job runtime data
FIRM_DATA_TABLES = (
    "users",
    "permissions",
    "roles",
    "role_permissions",
    "user_roles",
    "cases",
    "vuln_scanners",
    "vuln_scan_policies",
    "vuln_agents",
    "vuln_credential_refs",
    "vuln_asv_providers",
    "vuln_alert_thresholds",
    "vuln_custom_checks",
    "vuln_asset_owners",
)

FIRM_SCHEMA = "firm_aetheris"


def _docker_psql_dump(args: list[str]) -> bytes:
    cmd = [
        "docker",
        "compose",
        "-f",
        str(COMPOSE),
        "exec",
        "-T",
        "postgres",
        "pg_dump",
        "-U",
        "forensic",
        "-d",
        "forensic",
        "--no-owner",
        "--no-acl",
        *args,
    ]
    proc = subprocess.run(cmd, cwd=REPO, capture_output=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stderr.decode("utf-8", errors="replace"))
        raise RuntimeError(f"pg_dump failed: {' '.join(args)}")
    return proc.stdout


def _write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def _existing_tables(schema: str, names: tuple[str, ...]) -> list[str]:
    listed = subprocess.run(
        [
            "docker",
            "compose",
            "-f",
            str(COMPOSE),
            "exec",
            "-T",
            "postgres",
            "psql",
            "-U",
            "forensic",
            "-d",
            "forensic",
            "-At",
            "-c",
            (
                "SELECT tablename FROM pg_tables "
                f"WHERE schemaname = '{schema}' "
                f"AND tablename = ANY(ARRAY[{','.join(repr(n) for n in names)}]) "
                "ORDER BY tablename;"
            ),
        ],
        cwd=REPO,
        capture_output=True,
        text=True,
        check=True,
    )
    return [line.strip() for line in listed.stdout.splitlines() if line.strip()]


def main() -> None:
    if OUT.exists():
        import shutil

        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    schema_sql = _docker_psql_dump(["--schema-only", "--schema=public", f"--schema={FIRM_SCHEMA}"])
    header = (
        "-- ============================================================\n"
        "-- FULL SCHEMA DUMP (extensions, tables, indexes, constraints,\n"
        "-- functions/SPs, triggers, sequences) for public + firm_aetheris\n"
        "-- Generated by scripts/export_database_sql_bundle.py\n"
        "-- ============================================================\n\n"
        "CREATE EXTENSION IF NOT EXISTS pgcrypto;\n"
        "CREATE EXTENSION IF NOT EXISTS vector;\n\n"
    )
    _write(OUT / "01_extensions_and_schema.sql", header.encode("utf-8") + schema_sql)

    public_args = ["--data-only", "--column-inserts", "--rows-per-insert=50"]
    for table in PUBLIC_DATA_TABLES:
        public_args.extend(["-t", f"public.{table}"])
    public_data = _docker_psql_dump(public_args)
    _write(
        OUT / "02_data_public_master.sql",
        (
            "-- ============================================================\n"
            "-- STATIC / MASTER DATA (public)\n"
            "-- firms, platform RBAC, AXIOM catalog, report templates,\n"
            "-- case types, reports_artifacts, reports_objective, encyclopedia\n"
            "-- ============================================================\n\n"
        ).encode("utf-8")
        + public_data,
    )

    firm_tables = _existing_tables(FIRM_SCHEMA, FIRM_DATA_TABLES)
    firm_args = ["--data-only", "--column-inserts", "--rows-per-insert=50"]
    for table in firm_tables:
        firm_args.extend(["-t", f"{FIRM_SCHEMA}.{table}"])
    firm_data = _docker_psql_dump(firm_args) if firm_tables else b"-- (no firm IAM tables found)\n"
    _write(
        OUT / "03_data_firm_aetheris.sql",
        (
            "-- ============================================================\n"
            "-- TENANT Aetheris (firm_aetheris): roles, rights, users, cases\n"
            "-- Job runtime tables intentionally omitted (empty after cleanup)\n"
            "-- ============================================================\n\n"
            f'SET search_path TO "{FIRM_SCHEMA}", public;\n\n'
        ).encode("utf-8")
        + firm_data,
    )

    readme = f"""# database_sql — full schema + static/master seed

Exported from the live `forensic` database after deleting all forensic jobs
and job-related rows. Master catalogs, roles, rights, tenants, and users are kept.

## Dummy users

| Role | Tenant | Username / Email | Password |
|------|--------|------------------|----------|
| Superadmin | None | `superadmin@admin.com` | `admin@123456789` |
| Admin | Aetheris | `admin@aetheris.in` | `admin@123456789` |

## Apply (empty Postgres)

```powershell
cd E:\\rag_new2
.\\database_sql\\run-all.ps1
```

## Files

| File | Contents |
|------|----------|
| `01_extensions_and_schema.sql` | CREATE EXTENSION, TABLE, INDEX, FUNCTION/SP, TRIGGER, FK |
| `02_data_public_master.sql` | INSERT for firms, platform RBAC, AXIOM, report objectives/artifacts/procedures, case types |
| `03_data_firm_aetheris.sql` | INSERT for Aetheris roles, permissions, admin user, default cases |

Job tables exist in the schema dump but have **no data** (cleaned).

## Regenerate

```powershell
# after job cleanup
python scripts/export_database_sql_bundle.py
```
"""
    _write(OUT / "00_README.md", readme)

    files = [
        "01_extensions_and_schema.sql",
        "02_data_public_master.sql",
        "03_data_firm_aetheris.sql",
    ]
    ps1 = """# Apply database_sql bundle (requires docker compose postgres)
$ErrorActionPreference = "Stop"
$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Repo = Split-Path -Parent $Root
$files = @(
"""
    ps1 += ",\n".join(f'    "{f}"' for f in files)
    ps1 += """
)
foreach ($rel in $files) {
    $path = Join-Path $Root $rel
    Write-Host "Applying $rel ..."
    Get-Content $path -Raw | docker compose -f (Join-Path $Repo "docker-compose.yml") exec -T postgres `
        psql -U forensic -d forensic -v ON_ERROR_STOP=1
}
Write-Host "Done."
"""
    _write(OUT / "run-all.ps1", ps1)

    sh = "#!/usr/bin/env bash\nset -euo pipefail\nROOT=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\nREPO=\"$(cd \"$ROOT/..\" && pwd)\"\n"
    for rel in files:
        sh += f'echo "Applying {rel} ..."\n'
        sh += (
            f'docker compose -f "$REPO/docker-compose.yml" exec -T postgres '
            f'psql -U forensic -d forensic -v ON_ERROR_STOP=1 < "$ROOT/{rel}"\n'
        )
    sh += 'echo "Done."\n'
    _write(OUT / "run-all.sh", sh)

    run_all_sql = "-- Apply in order\n\\set ON_ERROR_STOP on\n\n" + "\n".join(f"\\i {f}" for f in files) + "\n"
    _write(OUT / "run-all.sql", run_all_sql)

    sizes = {f: (OUT / f).stat().st_size for f in files}
    print(f"Wrote {OUT}")
    for name, size in sizes.items():
        print(f"  {name}: {size:,} bytes")


if __name__ == "__main__":
    main()
